dist: xenial
# Use the latest Travis images since they are more up to date than the stable release.
group: edge
services:
  - docker
matrix:
  include:
    - env: js-tests
      language: node_js
      # The Node version here must be kept in sync with that in `package.json`.
      node_js: '12.13.0'
      cache: yarn
      before_install:
        # Try to keep version in sync with `package.json`
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.1
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - yarn install --frozen-lockfile
      script:
        # `yarn build` is tested as part of the Selenium job.
        - yarn lint
        # `yarn lint` only checks the formatting of JS/JSX, this will also check CSS/HTML/JSON/Markdown/YAML.
        - yarn format:check
        - yarn test:coverage
      after_success: yarn codecov

    - env: test-prod-build
      language: node_js
      # The Node version here must be kept in sync with that in `package.json`.
      node_js: '12.13.0'
      install:
        - yarn install --prod --frozen-lockfile
      script:
        - yarn build

    - env: python-linters
      language: python
      python: '3.7'
      cache:
        directories:
          - ${HOME}/venv
      install:
        - pip install -r requirements/common.txt
        - pip install -r requirements/dev.txt
        - pip install -r requirements/docs.txt
      script:
        - git grep -El '^#!/.+\b(bash|sh)\b' | xargs shellcheck
        - ./runchecks.sh

    - env: python-tests-main
      language: minimal
      install:
        - docker-compose build
        - pip install codecov --user
      script:
        - docker-compose run backend bash -c "pytest --cov --cov-report=xml tests/ --ignore=tests/selenium"
      after_success:
        - codecov -f coverage.xml

    - env: python-tests-selenium
      language: node_js
      # The Node version here must be kept in sync with that in `package.json`.
      node_js: '12.13.0'
      cache:
        directories:
          - node_modules
      before_install:
        - docker-compose build
      install:
        - yarn install
        - pip install codecov --user
      before_script:
        # Run in `before_script` to prevent the Selenium tests from running if the UI build fails.
        - yarn build
      script:
        # Several security features in settings.py (eg setting HSTS headers) are conditional on
        # 'https://' being in the site URL. In addition, we override the test environment's debug
        # value so the tests pass. The real environment variable will be checked during deployment.
        - docker-compose run backend bash -c "SITE_URL=https://treeherder.dev TREEHERDER_DEBUG=False
          ./manage.py check --deploy --fail-level WARNING"
        - docker-compose run backend bash -c "pytest --cov --cov-report=xml tests/selenium/"
      after_success:
        - codecov -f coverage.xml

notifications:
  email:
    on_success: never
    on_failure: always
